### ISSUE TITLE
We could use single-directional channel

### ISSUE THREAD

**Issue by mingrammer** [mingrammer/go-codelab#4]
'Serve' method only send out their log data to logger not receive anything from that. And file logger only receive the log data from outside. 

So, we could use single-directional channel instead of bidirectional channel (normal channel strcut)

**Comment by lawrence-kaybob** [comment]
Implementation done! Check 8ee6b4c67379f898867a54377f03de7580644174.
P.S. Previously, error occurs when 'log' directory doesn't exist. When 'log' directory exists, but there's no log file, `os.OpenFile` method automatically creates log file without error. So 'os.Open() & (*File).Stat()' checks whether directory exists.
